### ISSUE TITLE
E86: Buffer does not exist

### ISSUE THREAD

**Issue by Steadyx** [kdav5758/TrueZen.nvim#1] opened 2021-04-20 14:57 UTC
It appears that when I run TZAtaraxis I get the error stated above. The buffer changes every time. 

I'm running Neovim 0.5 
Alacritty
OSX

<img width="1057" alt="Screenshot 2021-04-20 at 15 56 23" src="https://user-images.githubusercontent.com/13971238/115418133-267f4f80-a1f1-11eb-9e71-b52e8756bbc9.png">

**Comment by kdav5758** [comment] 2021-04-20 19:13
Before the Ataraxis feature was introduced, I, with the help of some volunteers, tested this feature under different scenarios and it passed all of them.

Could you provide instructions to reproduce it please?

**Comment by Steadyx** [comment] 2021-04-20 19:33
Hey there, I'll run you through the steps. 

I installed the plugin, I currently use packer and my config is in lua. Once installed I restarted vim and tested the plugin out. In command mode, I ran TZAtaraxis which resulted in the error in the picture above. I read a comment regarding bugs for statuslines so I removed my statusline and tried again but the error was still occurring when I ran TZAtaraxis in command mode.

**Comment by EthanJWright** [comment] 2021-04-21 17:03
I would like to add that I'm hitting the same bug. 

I'm on the nightly neovim install:

`$ nvim --version
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3`

I added the plugin using Plug:

`Plug 'kdav5758/TrueZen.nvim'`

Then I started a fresh test file:
`nvim test.py`

And then ran TZAtaraxi:

`:TZAtaraxis`

with the following results:
![error](https://user-images.githubusercontent.com/14322242/115592980-2898eb00-a291-11eb-99f1-542070e70069.png)

**Comment by codingjerk** [comment] 2021-04-21 17:56
I'm getting exactly the same result and the error message

**Comment by nadir-yttrium** [comment] 2021-04-21 18:52
Same issue here, same error message.

**Comment by kdav5758** [comment] 2021-04-22 04:34
Hello there! First of all, excuse me for the late reply, I was working on other features and solving other issues...

Second of all, since there was so much new stuff merged to main since you opened this issue I'd first recommend you uninstalling the plug-in and installing it again (of course, configure it before using it), and then try Ataraxis mode and see if you still have the issue.

Side note: there is currently one issue with a broken hi group that I'll solve later, so of you get a message saying something in the lines of `E420: BG color unknown` then it's *normal* and unrelated to this issue.

**Comment by nadir-yttrium** [comment] 2021-04-22 04:49
Just wanted to check in and confirm that the issue remains for me after removing the plugin folder completely and installing the newest version. 

Thank you for your effort.

**Comment by ed-kemp** [comment] 2021-04-22 07:51
The issue is still occurring for me as well.

**Comment by lsrdg** [comment] 2021-04-22 10:12
Same issue, just installed the plugin. Setup:
Archlinux, Termite, NVIM v0.5.0-dev+1250-gcd3e74201, Packer. Error message:

`E5108: Error executing lua ...tart/TrueZen.nvim/lua/services/mode-ataraxis/service.lua:337: Vim(buffer):E86: Buffer 5 does not exist`

Other than that, the plugin looks really promising. (:

**Comment by kdav5758** [comment] 2021-04-22 12:26
Unfortunately, I haven't been able to reproduce the issue. It seems to be related to something in your config(s). Could anybody PM me on Reddit to discuss this issue further?
This is me: https://www.reddit.com/user/sebas5758

**Comment by kdav5758** [comment] 2021-04-22 16:30
The issue was debugged! with the help of @Steadyx we found out that users must set `splitbelow` and `splitright` in their config. Therefore, in the case of *init.lua* users:
```lua
local cmd = vim.cmd

cmd("set splitbelow")
cmd("set splitright")
```

And for the case of *init.vim* users:
```
set splitbelow
set splitright
```

Personally I don't think is the users' responsibility to set this options in their configs, so I'm going to make it so that the plugin will set and unset those vars when needed. Again, thank you @Steadyx for helping me debug this issue! as of now, you can use this a workaround. The real fix will come in a few minutes...

Side note: if you are also having issues with your colorscheme then `set termguicolors`

**Closed by kdav5758** 2021-04-22 16:30 UTC

**Comment by kdav5758** [comment] 2021-04-22 17:12
The bug was fixed and it was merged to main. Now, users with or without the aforementioned settings can enjoy Ataraxis mode. Here is the commit: https://github.com/kdav5758/TrueZen.nvim/commit/b5434f36a6c238f2d606026a281a043cf5b32ce0

Just update it! it'll work out-of-the-box now :)
