### ISSUE TITLE
exit while in ataraxis mode

### ISSUE THREAD

**Issue by LuisxSullivaN** [kdav5758/TrueZen.nvim#23] opened 2021-05-07 17:13 UTC
I don't know if it's just me, but when I'm in ataraxis mode and try to quit neovim (:q or ZZ)  it doesn't do that, actually have to repeat like 4 or 5 times more in order to quit in ataraxis mode even when the buffer hasn't been modified.

Edit: I forgot to mention that also when I successfully quit in atarixs mode my tmux statusline doesn't come back, I have to enter vim again and run TZAtaraxis twice to get it back

**Comment by YaBoiBurner** [comment] 2021-05-07 17:34
I'm guessing that the tmux issue is caused by the tmux integration not running on either the `VimLeavePre` or `VimLeave` events. The integration just runs `tmux set -g status on` and `tmux set -g status off`.

I can't test it all that easily, but the easiest workaround for that is probably just turning off the tmux integration for now.

I know that there's _some_ way to make the buffers close when vim exits by default, but I haven't figured out how.

**Comment by LuisxSullivaN** [comment] 2021-05-07 17:37
Found out ataraxis mode creates 3 different windows and that's why it requires multiple quits. Running :qa exits fine for now. Thanks for your response.

**Comment by flaturtha** [comment] 2021-05-07 18:24
I found that using :qall quits me out of all of it in one command.

**Comment by kdav5758** [comment] 2021-05-07 19:25
Haha don't worry actually expected behavior. Ataraxis mode creates four buffers (if their size in the settings is not zero] and hides all of their components so that it can give that "padding" effect. Because of that, if you quit the middle buffer with `:q` (which is the one you always end up at when you first enter Ataraxis mode), the other four invisible buffers will stay there.

I actually thought about implementing this for "fusing :q with :TZAtaraxisT" so that you could just quit with `:q`. I don't really know why I never implemented this. 

Would you like me to develop it [PRs are welcomed too]?

**Comment by kdav5758** [comment] 2021-05-08 17:21
Nevermind. Nobody replied, but still, I think it's a cool feature to have, so I made it:

https://user-images.githubusercontent.com/58336662/117547756-f3adc780-aff6-11eb-9a3c-407359d03880.mp4


Of course you won't see the little text that appear in the end (that was just for me while I was testing it). The feature is ready and merged to the `dev` branch, but I still need to update the doc. In the mean time you can grab `dev`, and use it by enabling this setting:

![image](https://user-images.githubusercontent.com/58336662/117547833-60c15d00-aff7-11eb-85c4-a6044383e1a1.png)

The only thing I'm not quit sure of is whether it should be enabled or disabled by default. Right now it's **off** by default.

**Closed by kdav5758** 2021-05-08 17:21 UTC

**Comment by LuisxSullivaN** [comment] 2021-05-10 04:52
Thanks @kdav5758, will look into it!
